[package]
name = "dail"
version = "0.1.2"
edition = "2024"
license = "BSD-3-Clause"
description = "Daily jail management for FreeBSD"
homepage = "https://github.com/zeslava/dail"
repository = "https://github.com/zeslava/dail"

[[bin]]
name = "dail"
path = "src/main.rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
toml = "0.8"
thiserror = "2"
anyhow = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4", features = ["derive"] }
clap_complete = { version = "4", features = ["unstable-dynamic"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4", "serde"] }
tempfile = "3"
libc = "0.2"
glob = "0.3.3"
