PORTNAME=	dail
DISTVERSIONPREFIX=	v
DISTVERSION=	0.1.0
CATEGORIES=	sysutils

MAINTAINER=	your@email.here
COMMENT=	Daily jail management for FreeBSD
WWW=		https://github.com/zeslava/dail

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cargo
USE_GITHUB=	yes
GH_ACCOUNT=	zeslava

PLIST_FILES=	bin/dail

# Uncomment after running: make cargo-crates && make makesum
# CARGO_CRATES=	...

.include <bsd.port.mk>
